services:
  laravel-app:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www/n8n_automation
    user: "1000:1000"
    depends_on:
      - mysql
      - n8n
    networks:
      - n8n-automation-network

  nginx:
    image: nginx:alpine
    container_name: n8n_automation_nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/n8n_automation
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app
    networks:
      - n8n-automation-network

  mysql:
    image: mysql:8.0
    container_name: n8n_automation_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./.docker/mysql:/docker-entrypoint-initdb.d

    networks:
      - n8n-automation-network

  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_automation_n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
    volumes:
      - n8n-data:/home/node/.n8n
    networks:
      - n8n-automation-network

networks:
  n8n-automation-network:
    driver: bridge

volumes:
  mysql-data:
  n8n-data:
